# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UlvVMelI_nl6RB9GyyJ9cjJzjAnBntbq
"""

!pip install pytesseract
!pip install pillow
!sudo apt install tesseract-ocr

import pytesseract
from PIL import Image

rasm = Image.open('photo_2024-12-04_20-23-50.jpg')


matn = pytesseract.image_to_string(rasm)
print("Rasmdagi matn:")
print(matn)

